runtime: custom
env: flex
manual_scaling:
  instances: 1
env_variables:
  # The __ in My__Greeting will be translated to a : by ASP.NET.
  Company__Name: "AFORO255"
  Company__Author: "STYWAR VARGAS"  